### ISSUE TITLE
未登录也能收藏

### ISSUE THREAD

**Issue by Brawns** [DreamTom/InternetInterview#1]
进去不选择登录，点击收藏按钮，也能收藏成功，不知道这种情况在你的小程序里面是否属于正常情况？

**Comment by DreamTom** [comment]
是属于正常情况，本小程序采用的静默登录 第一次打开之后就相当于登录，那个微信授权只是为了展示头像

**Comment by Brawns** [comment]
ok 了解

**Comment by DreamTom** [comment]
> ok 了解 

小程序重新上线啦
